const projects = [
    {
        id:1,
        name:"AiContentDetector",
        image:"https://i.postimg.cc/L5WqYnH7/Ai-Content-Detector.png",
        demo:"https://typle-ai-content-detector.netlify.app",
        github:"https://github.com/aungpyaephyo1412/AI-Content-Detector",
        skills:["Javascript","Tailwindcss","Reactjs","Axios","Rapid-Api"]
    },
    {
        id:2,
        name:"ChatGpt",
        image:"https://i.postimg.cc/VNwJCy8Y/chatgpt.png",
        demo:"https://typle-open-ai.netlify.app",
        github:"https://github.com/aungpyaephyo1412/Open_AI",
        skills:["Javascript","Tailwindcss","Reactjs","Axios","Rapid-Api"]
    },
    {
        id:3,
        name:"Facebook",
        image:"https://i.postimg.cc/x10yc1Kj/facebook.png",
        demo:"https://typle-facebook.netlify.app",
        github:"https://github.com/aungpyaephyo1412/fb-clone",
        skills:["Javascript","Bootstrap","SASS"]
    },
    {
        id:4,
        name:"Flyo",
        image:"https://i.postimg.cc/X7V679Dr/flyo.png",
        demo:"https://typle-flyo.netlify.app",
        github:"https://github.com/aungpyaephyo1412/",
        skills:["Javascript","Bootstrap","SASS"]
    },
    {
        id:5,
        name:"Sushi",
        image:"https://i.postimg.cc/FKk2np1B/foodie.png",
        demo:"https://typle-sushi.netlify.app",
        github:"https://github.com/aungpyaephyo1412/sushi",
        skills:["Javascript","Bootstrap","SASS"]
    },
    {
        id:6,
        name:"Foodie",
        image:"https://i.postimg.cc/jSFpXmqf/foodie-1.png",
        demo:"https://typle-foodie.netlify.app",
        github:"https://github.com/aungpyaephyo1412/react-foodie",
        skills:["Javascript","Bootstrap","SASS"]
    },
    {
        id:7,
        name:"Foodie Menu",
        image:"https://i.postimg.cc/NM1ZQ068/foodiemenu.png",
        demo:"https://majestic-alpaca-da1457.netlify.app",
        github:"https://github.com/aungpyaephyo1412/react-foodie",
        skills:["Javascript","Tailwindcss","Reactjs","Redux","RestFul-Api"]
    },
    {
        id:8,
        name:"Foodie Detail",
        image:"https://i.postimg.cc/B6WdWFKQ/foodiemenudetail.png",
        demo:"https://react-foodie-clone.netlify.app",
        github:"https://github.com/aungpyaephyo1412/react-foodie",
        skills:["Javascript","Tailwindcss","Reactjs","Redux","RestFul-Api"]
    },
    {
        id:9,
        name:"Google Translate",
        image:"https://i.postimg.cc/QNgr3fSL/googletranslate.png",
        demo:"https://typle-google-translate.netlify.app",
        github:"https://github.com/aungpyaephyo1412/google-translate",
        skills:["Javascript","Tailwindcss","Reactjs","Axios","Rapid-Api"]
    },
    {
        id:10,
        name:"Medium",
        image:"https://i.postimg.cc/MKd2cXhd/mediumclone.png",
        demo:"https://mediun-blog-example-template.netlify.app",
        github:"https://github.com/aungpyaephyo1412/Mediun-Blog-Example-Template",
        skills:["Javascript","Bootstrap","SASS"]
    },
    {
        id:11,
        name:"MMS Shop",
        image:"https://i.postimg.cc/Jz0wjM8m/mmshop.png",
        demo:"https://lively-kashata-5878f6.netlify.app",
        github:"https://github.com/aungpyaephyo1412/swd-shop",
        skills:["Javascript","Bootstrap","SASS","Axios","RestFul-Api"]
    },
    {
        id:12,
        name:"QR Generator",
        image:"https://i.postimg.cc/R0tDT0Dr/qrcodegenerator.png",
        demo:"https://typle-qr-code-generator.netlify.app",
        github:"https://github.com/aungpyaephyo1412/QR_CODE_GENERATOR_JS",
        skills:["Javascript","Tailwindcss"]
    },
    {
        id:13,
        name:"Parallax",
        image:"https://i.postimg.cc/d3sNvjtv/reactparallax.png",
        demo:"https://typle-react-parallax.netlify.app",
        github:"https://github.com/aungpyaephyo1412/react_parallax",
        skills:["Javascript","Tailwindcss","Reactjs"]
    },
    {
        id:14,
        name:"RTK OS",
        image:"https://i.postimg.cc/G2JgZ5Rq/rtkos.png",
        demo:"https://rtk-os.netlify.app",
        github:"https://github.com/aungpyaephyo1412/rtk-os",
        skills:["Javascript","Tailwindcss","Reactjs","Redux","RestFul-Api"]
    },
    {
        id:15,
        name:"Image Generator",
        image:"https://i.postimg.cc/Znw7qvCN/unsplash.png",
        demo:"https://unsplash-generator.netlify.app",
        github:"https://github.com/aungpyaephyo1412/unsplash_generator",
        skills:["Javascript","Tailwindcss","Reactjs","Redux","Unsplash-Api"]
    }
]
export default projects